# Generated by Django 5.2.8 on 2025-12-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocontato',
            name='servico_realizado',
            field=models.BooleanField(default=False),
        ),
    ]
