# Generated by Django 5.2.8 on 2025-12-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacoes', '0002_solicitacaocontato_servico_realizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocontato',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
