# Generated by Django 5.2.8 on 2026-01-28 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacoes', '0003_solicitacaocontato_data_conclusao'),
        ('servicos', '0002_prestadorservicos_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocontato',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaocontato',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddIndex(
            model_name='solicitacaocontato',
            index=models.Index(fields=['is_deleted'], name='idx_solicitacao_deleted'),
        ),
    ]
