# Generated by Django 5.2.8 on 2025-11-28 19:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('solicitacao_contato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='contratacoes.solicitacaocontato')),
            ],
            options={
                'ordering': ['-data_criacao'],
                'unique_together': {('solicitacao_contato',)},
            },
        ),
    ]
