# Generated by Django 5.2.8 on 2025-11-28 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestadorprofile',
            name='servicos',
            field=models.ManyToManyField(related_name='prestadores', to='servicos.servico'),
        ),
        migrations.AddField(
            model_name='prestadorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_prestador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='prestadorprofile',
            index=models.Index(fields=['cep'], name='idx_cep'),
        ),
        migrations.AddIndex(
            model_name='prestadorprofile',
            index=models.Index(fields=['latitude', 'longitude'], name='idx_geo'),
        ),
    ]
