# Generated by Django 5.2.8 on 2025-11-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_prestadorprofile_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteprofile',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='clienteprofile',
            name='complemento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clienteprofile',
            name='numero_casa',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clienteprofile',
            name='rua',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='clienteprofile',
            name='telefone_contato',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='prestadorprofile',
            name='biografia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prestadorprofile',
            name='telefone_publico',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(help_text='CPF sem pontuação', max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dt_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('T', 'Trans'), ('N', 'Não binário'), ('O', 'Outro'), ('P', 'Prefiro não informar')], max_length=1, null=True),
        ),
    ]
