# Generated by Django 5.2.8 on 2025-11-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_clienteprofile_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteprofile',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prestadorprofile',
            name='biografia',
            field=models.TextField(blank=True),
        ),
    ]
