# Generated by Django 5.2.8 on 2025-11-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_clienteprofile_complemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestadorprofile',
            name='nota_media_cache',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=3),
        ),
    ]
