# Generated by Django 5.2.8 on 2025-12-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_prestadorprofile_nota_media_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteprofile',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritado_por', to='accounts.prestadorprofile'),
        ),
    ]
