# Generated by Django 5.2.8 on 2025-12-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_clienteprofile_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestadorprofile',
            name='servicos_nao_realizados_cache',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
