# Generated by Django 5.2.8 on 2026-01-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_additional_users'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='clienteprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='clienteprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='prestadorprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prestadorprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddIndex(
            model_name='clienteprofile',
            index=models.Index(fields=['is_deleted'], name='idx_cliente_deleted'),
        ),
        migrations.AddIndex(
            model_name='prestadorprofile',
            index=models.Index(fields=['is_deleted'], name='idx_prestador_deleted'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted'], name='idx_user_deleted'),
        ),
    ]
