# Generated by Django 5.2.8 on 2025-11-28 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.ImageField(blank=True, null=True, upload_to='icones_categorias/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='servicos.categoriaservico')),
            ],
        ),
        migrations.CreateModel(
            name='PrestadorServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestador_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.prestadorprofile')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Serviço do prestador',
                'verbose_name_plural': 'Prestador - Serviços',
            },
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['categoria'], name='idx_categoria'),
        ),
        migrations.AlterUniqueTogether(
            name='prestadorservicos',
            unique_together={('prestador_profile', 'servico')},
        ),
    ]
