# Generated by Django 5.2.8 on 2025-11-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
