# Generated by Django 5.2.8 on 2026-01-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_options_alter_user_managers_and_more'),
        ('portfolio', '0002_alter_portfolioitem_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['is_deleted'], name='idx_portfolio_deleted'),
        ),
    ]
